"""fix_missing_columns

Revision ID: 8e659a64e58c
Revises: 35e8668da283
Create Date: 2026-02-25 18:39:09.029685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e659a64e58c'
down_revision: Union[str, Sequence[str], None] = '35e8668da283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('wallet_echoes', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('shards', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('reputation', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reputation')
    op.drop_column('users', 'shards')
    op.drop_column('users', 'wallet_echoes')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
