"""Added templates

Revision ID: ed9ca4250f74
Revises: 901453b9a534
Create Date: 2026-05-03 17:16:47.402913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed9ca4250f74'
down_revision: Union[str, Sequence[str], None] = '901453b9a534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    conn = op.get_bind()
    conn.execute(sa.text("SELECT 1")) #
    op.create_table('card_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_power', sa.Integer(), nullable=False),
    sa.Column('rarity_type', sa.String(), nullable=False), 
    sa.Column('ghost_family', sa.String(), nullable=False),
    sa.Column('image_asset', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("ALTER TABLE card_template ALTER COLUMN rarity_type TYPE cardrarity USING rarity_type::cardrarity")
    op.execute("ALTER TABLE card_template ALTER COLUMN ghost_family TYPE ghostfamily USING ghost_family::ghostfamily")
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_skills',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['card_template.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'skill_id')
    )
    op.add_column('cards', sa.Column('template_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cards', 'card_template', ['template_id'], ['id'])
    op.drop_column('cards', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('type', postgresql.ENUM('TYPE1', 'TYPE2', 'TYPE3', name='ghostfamily'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'template_id')
    op.drop_table('card_skills')
    op.drop_table('skills')
    op.drop_table('card_template')
    # ### end Alembic commands ###
